import os

def menuPrincipal():
    print (chr(27)+"[1;33m" + "="*100)
    cadena = "bienvenido a Restaurant App".upper() 
    print (cadena.center(100, "="))
    print ("="*100)
    print ("\n")
    print ("Por favor seleccione la opcion adecuada".upper().center(100, "="))
    print ("\n")
    print (chr(27)+"[3;32m" + "1.    Clientes".ljust(100, " "))
    print ("2.    Productos".ljust(100, " "))
    print ("3.    Pedidos".ljust(100, " "))
    print ("4.    Facturas".ljust(100, " "))
    print ("5.    Categorias".ljust(100, " "))
    print ("6.    Salir".ljust(100, " "))
    print ("\n")
    print (chr(27)+"[1;33m" + "="*100)
    seleccion = int(input("Ingrese el valor correspondiente: "))
    print ("="*100)
    os.system('cls')
    return seleccion

def menuClientes():
    print (chr(27)+"[1;33m" +"="*100)
    cadena = "Modulo Clientes".upper() 
    print (cadena.center(100, "="))
    print ("="*100)
    print ("\n")
    print ("Por favor seleccione la opcion adecuada".upper().center(100, "="))
    print ("\n")
    print (chr(27)+"[3;36m" + "1.    Mostrar Clientes".ljust(100, " "))
    print ("2.    Agregar Cliente".ljust(100, " "))
    print ("3.    Actualizar Cliente".ljust(100, " "))
    print ("4.    Eliminar Cliente".ljust(100, " "))
    print ("5.    Regresar".ljust(100, " "))
    print ("\n")
    print (chr(27)+"[1;33m" + "="*100)
    seleccion = int(input("Ingrese el valor correspondiente: "))
    print ("="*100)
    os.system('cls')
    return seleccion

def menuProductos():
    print (chr(27)+"[1;33m" +"="*100)
    cadena = "Modulo Productos".upper() 
    print (cadena.center(100, "="))
    print ("="*100)
    print ("\n")
    print ("Por favor seleccione la opcion adecuada".upper().center(100, "="))
    print ("\n")
    print (chr(27)+"[3;36m" + "1.    Mostrar Productos".ljust(100, " "))
    print ("2.    Agregar Producto".ljust(100, " "))
    print ("3.    Actualizar Producto".ljust(100, " "))
    print ("4.    Eliminar Producto".ljust(100, " "))
    print ("5.    Regresar".ljust(100, " "))
    print ("\n")
    print (chr(27)+"[1;33m" + "="*100)
    seleccion = int(input("Ingrese el valor correspondiente: "))
    print ("="*100)
    os.system('cls')
    return seleccion

def menuPedidos():
    print ("="*100)
    cadena = "Modulo Pedidos".upper() 
    print (cadena.center(100, "="))
    print ("="*100)
    print ("\n")
    print ("Por favor seleccione la opcion adecuada".upper().center(100, "="))
    print ("\n")
    print ("1.    Mostrar Pedidos".ljust(100, " "))
    print ("2.    Agregar Pedido".ljust(100, " "))
    print ("3.    Actualizar Pedido".ljust(100, " "))
    print ("4.    Eliminar Pedido".ljust(100, " "))
    print ("5.    Regresar".ljust(100, " "))
    print ("\n")
    print ("="*100)
    seleccion = int(input("Ingrese el valor correspondiente: "))
    print ("="*100)
    os.system('cls')
    return seleccion

def menuFacturas():
    print ("="*100)
    cadena = "Modulo Facturas".upper() 
    print (cadena.center(100, "="))
    print ("="*100)
    print ("\n")
    print ("Por favor seleccione la opcion adecuada".upper().center(100, "="))
    print ("\n")
    print ("1.    Mostrar Facturas".ljust(100, " "))
    print ("2.    Agregar Factura".ljust(100, " "))
    print ("3.    Actualizar Factura".ljust(100, " "))
    print ("4.    Eliminar Factura".ljust(100, " "))
    print ("5.    Regresar".ljust(100, " "))
    print ("\n")
    print ("="*100)
    seleccion = int(input("Ingrese el valor correspondiente: "))
    print ("="*100)
    os.system('cls')
    return seleccion

def menuCategorias():
    print ("="*100)
    cadena = "Modulo Categorias".upper() 
    print (cadena.center(100, "="))
    print ("="*100)
    print ("\n")
    print ("Por favor seleccione la opcion adecuada".upper().center(100, "="))
    print ("\n")
    print ("1.    Mostrar Categorias".ljust(100, " "))
    print ("2.    Agregar Categoria".ljust(100, " "))
    print ("3.    Actualizar Categoria".ljust(100, " "))
    print ("4.    Eliminar Categoria".ljust(100, " "))
    print ("5.    Regresar".ljust(100, " "))
    print ("\n")
    print ("="*100)
    seleccion = int(input("Ingrese el valor correspondiente: "))
    print ("="*100)
    os.system('cls')
    return seleccion


# menuPrincipal()
# menuClientes()
# menuCategorias()